<?php
//Class Car{
//    private $name_car="Lambo";
//    protected $price="10000";
//    public $location="TV";
//    public static $year="2020";
//    private function name(){
//        return $this->name_car;
//    }
//    protected function price_car(){
//        return $this->price();
//    }
//
//}
//Class Morning extends Car {
//    public function get_location(){
//        return $this->location;
//    }
//    public function get_price(){
//        return self::$year;
//    }
//}
//
//$getcar = new Morning;
//echo $getcar->get_location();
//echo $getcar->get_price();
//echo Car::$year;
//$car = new Car;
class a
{
    private $t;
    public function test_1()
    {
        echo "a";
    }

    protected function test_2()
    {
        echo "b";
    }

    private function test_3()
    {
        echo "c";
    }

    public static function test_4()
    {
        echo 'd';
    }
    //call function on class
    //$this->test_1();
    public function test_seft(){
        return self::test_4();
    }
}

class b extends a
{
    public function test_1()
    {
        // parent::test_1(); // TODO: Change the autogenerated stub
        //echo"a ex b";
        return $this->test_2();
    }

    protected function test_2()
    {
        // parent::test_2(); // TODO: Change the autogenerated stub
        echo "overline";
    }

}

class c extends b
{
    public function test_1()
    {
        // parent::test_1(); // TODO: Change the autogenerated stub
        echo "a ex c";
    }
}

$b = new b;
echo $b->test_1();
echo "<br>";
echo a::test_4();
echo $b->test_seft();
trait x{
    public function test(){
        echo 'x';
    }
}
trait y{
    public function test1(){
        echo 'y';
    }
}
class test_trait {
    use y;
   // use x;
    public  function  test(){
        ECHO 'Z';
    }
}
$trait = new test_trait;
echo'<br>---------';
echo $trait->test();
